In [1]:
import numpy as np

In [3]:
a = np.random.randint(1, 9, size = (3,3))
a

array([[1, 8, 4],
       [7, 5, 4],
       [6, 8, 7]])

In [4]:
a.tolist()

[[1, 8, 4], [7, 5, 4], [6, 8, 7]]

In [6]:
a.trace()

13

In [8]:
a[a>2]

array([8, 4, 7, 5, 4, 6, 8, 7])

In [10]:
b = np.random.randint(1, 9, size = (3,3))
b

array([[6, 8, 4],
       [8, 3, 6],
       [4, 4, 8]])

In [17]:
l , c = a.shape

In [18]:
C = np.zeros(a.shape)
for i in range (l):
    for j in range (c):
        C[i, j] = a[i, j] + b[i, j]
        
print(C)

[[ 7. 16.  8.]
 [15.  8. 10.]
 [10. 12. 15.]]


In [22]:
m = a.mean(axis = 1)

In [23]:
print(a-m)

[[-3.33333333  2.66666667 -3.        ]
 [ 2.66666667 -0.33333333 -3.        ]
 [ 1.66666667  2.66666667  0.        ]]
